Update hooks-effect.md
reactjs/tr.reactjs.org pull request #245
Opened 2020-11-29 16:01 UTC by EngincanV

2020-11-30 13:13 UTC, alioguzhan requested changes
Thanks for the translation. Left a comment just for one place. Please check.

2020-11-30 13:13 UTC, alioguzhan commented on content/docs/hooks-effect.md
> +Tebrikler! Bu uzun bir sayfaydı, ama umarım sonunda etkilerle ilgili sorularınızın çoğu yanıtlanmıştır. Hem State Hook'unu hem de Effect Hook'unu öğrendiniz ve ikisini birleştirerek yapabileceğiniz *
`umarim` -> `umariz`

2020-11-30 15:13 UTC, EngincanV commented
@alioguzhan required change has been made.

2020-12-01 07:40 UTC, alioguzhan approved these changes

2020-12-01 07:40 UTC, alioguzhan commented
Thanks for the translation. Merging it...

2020-12-01 07:40 UTC, merged