translate concurrent mode intro
reactjs/tr.reactjs.org pull request #253
Opened 2020-12-21 17:57 UTC by ataberkgrl

2020-12-21 20:15 UTC, alioguzhan requested changes
Thanks for the translation. This is great. I left some comments to point out some places that can be / should be updated. Please see my review.

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +Takılmanın sebebi gayet basit bir şekilde açıklanabilir: render, edilmeye başlandığı anda yarıda kesilemez. Bu durumda tarayıcı, girdiyi tuşa basılmasının hemen ardından güncelleyemez. Her ne kadar k
To make things clear: 
> Render işlemi, başladıktan sonra yarıda kesilemez.

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +**Eşzamanlı Mod render etmeyi yarıda kesilebilir şekilde uygulayarak bu temel sınırlamayı ortadan kaldırır.** Bu durum, kullanıcı başka bir tuşa bastığında, tarayıcının girdiyi güncellemesinin React
comma after `Eszamanli Mod`:

> Eşzamanlı Mod, render işlemini yarıda kesilebilir hale getirerek bu temel sınırlamayı ortadan kaldırır.

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +Günümüzde bu her ne kadar uygulanabilir olsa da app içerisindeki uyumluluğu sağlaması oldukça zorlayıcı olabilir. Eşzamanlı Mod'da bu özellik hazır olarak bulunmaktadır. Öncelikle, React yeni ekranı
- Comma after `olsa da`.

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +Bir app üzerinde iki farklı sayfa arasında geçiş yaptığımızı hayal edin. Bazı durumlarda kullanıcıya yeterli kalitede bir yükleme sekansı veremeyecek kadar kod ya da veri yüklenmemiş olabilir. Boş bi
Maybe we can use `uygulama` instead of `app`. What do you think? There are several places that can be updated, I believe.

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +* IO'ya bağlı güncellemeler (ağ üzerinden kod ya da verinin alınması gibi) için eşzamanlılık, verinin tamamı henüz ulaşmamış olsa dahi React bellekte render işlemine başlayabilir ve kullanıcı deneyim
Maybe we can specify what `IO` stands for between brackets? What do you think?

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +Artık Eşzamanlı Mod'un ne olduğunu tamamen biliyorsun!
`biliyorsunuz` instead of `biliyorsun`

2020-12-21 20:15 UTC, alioguzhan commented on content/docs/concurrent-mode-intro.md
> +İleriki sayfalarda daha spesifik konular hakkında detaylar öğreneceksin:
`ogreneceksiniz` instead of `ogreneceksin`

2020-12-22 06:55 UTC, ataberkgrl commented
@alioguzhan thank you for your feedback! Those requests were very sensible and I updated the file just as you explained.

2020-12-22 07:38 UTC, yunusemredilber approved these changes
Eline sağlık :)

2020-12-22 09:05 UTC, alioguzhan approved these changes
Thanks for the fixes :) Great translation. Merging it...

2020-12-22 09:05 UTC, merged